// VerilogExporter — public entry for circuitJSON → Verilog.
//
// Three-stage pipeline:
//   1. validateCircuit → HDLError[]  (warnings surfaced, errors halt export)
//   2. fromCircuit     → IRModule    (structural, width-explicit IR)
//   3. toVerilog       → string      (deterministic pretty print)
//
// Identifier sanitization is re-exported from core/identifiers.js so that
// existing callers (Phase 1 tests) continue to import it from this module.

import { validateCircuit, hasBlockingErrors } from './core/CircuitValidator.js';
import { fromCircuit } from './ir/fromCircuit.js';
import { toVerilog } from './ir/toVerilog.js';
import { hasTranslator } from './translators/index.js';
import './translators/all.js';     // side-effect: registers every translator

export { sanitizeIdentifier } from './core/identifiers.js';
export { HDLError, SEVERITY } from './core/HDLError.js';

// Phase 8-10 import path: text → AST → IR → circuit.json. The full
// pipeline lives in the parser + import dirs; we re-export the
// convenience wrapper here so callers have one entry point.
export { parseVerilog }   from './parser/parser.js';
export { elaborate }      from './parser/elaborate.js';
export { toCircuit }      from './import/toCircuit.js';
export { autoLayout, autoLayoutAsync } from './import/autoLayout.js';
/**
 * One-shot Verilog import: text → circuit.json with auto-layout.
 * Throws on lex/parse errors; surfaces elaborate errors via the
 * `errors` field on the returned object. Pass `{ layout: false }` to
 * receive the raw circuit with every node at (0,0).
 */
export function importVerilog(text, opts = {}) {
  const { ast } = _parseVerilog(text, opts);
  const { ir, errors } = _elaborate(ast, { source: text, ...opts });
  if (!ir) return { circuit: null, errors };
  const circuit = _toCircuit(ir, opts);
  if (opts.layout !== false) _autoLayout(circuit, opts);
  return { circuit, errors };
}
// Local re-bindings so the wrapper above doesn't shadow the named
// exports (which the test suite imports directly).
import { parseVerilog as _parseVerilog } from './parser/parser.js';
import { elaborate    as _elaborate }    from './parser/elaborate.js';
import { toCircuit    as _toCircuit }    from './import/toCircuit.js';
import { autoLayout   as _autoLayout }   from './import/autoLayout.js';

// Determinism contract: exportCircuit output is byte-identical across runs
// for a given circuitJSON. A timestamp is emitted ONLY when the caller opts
// in with `timestamp: true`; without it, round-trip (export → copy → import
// → re-export) produces identical bytes.
function buildHeaderText({ header, timestamp }) {
  if (!header) return null;
  const line1 = 'Generated by Circuit Designer — HDL Toolchain';
  if (!timestamp) return line1;
  return `${line1}\nExported: ${new Date().toISOString()}`;
}

export function exportCircuit(circuitJSON, options = {}) {
  const opts = {
    topName: 'top',
    header: true,
    timestamp: false,
    ...options,
  };

  const errors = validateCircuit(circuitJSON, { hasTranslator });
  if (hasBlockingErrors(errors) && !opts.force) {
    // Blocking errors → throw the first. Callers that want the full list
    // should call validateCircuit directly or use exportCircuitWithDiagnostics.
    const first = errors.find(e => e.severity === 'error');
    throw first;
  }

  const ir = fromCircuit(circuitJSON, { synthesisSafe: opts.synthesisSafe });
  ir.name = opts.topName;

  // Build the header so it can include a tri-state preservation warning
  // when the user opted out of synthesisSafe.
  let extraHeader = '';
  if (opts.synthesisSafe === false && Array.isArray(ir._lowerTriStateDiagnostics)) {
    const warn = ir._lowerTriStateDiagnostics.find(d => d.kind === 'tristate-preserved');
    if (warn) extraHeader = `\nWARNING: ${warn.message}`;
  }
  const headerText = buildHeaderText(opts);
  const finalHeader = headerText && extraHeader
    ? headerText + extraHeader
    : (headerText || (extraHeader ? extraHeader.trim() : null));

  return toVerilog(ir, {
    header: !!opts.header || !!extraHeader,
    headerText: finalHeader,
  });
}

// Power-user entry: returns Verilog + diagnostic list + IR, never throws.
export function exportCircuitWithDiagnostics(circuitJSON, options = {}) {
  const opts = { header: true, timestamp: false, ...options };
  const errors = validateCircuit(circuitJSON, { hasTranslator });
  const ir = fromCircuit(circuitJSON);
  ir.name = opts.topName || 'top';
  const verilog = toVerilog(ir, {
    header: !!opts.header,
    headerText: buildHeaderText(opts),
  });
  return { verilog, errors, ir };
}
